<?php
$this->headTitle()->append($this->translate('Edit staff group'))
    ->append($this->translate('Staff'));

$this->formElementErrors()->setMessageOpenFormat(
    '<ul class="list-group text-danger">
                <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
)->setMessageSeparatorString(
    '</li>
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
);
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Edit staff group') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current()]) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>">
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <?php echo $this->form()->openTag($form); ?>
    <div class="panel panel-bordered">
        <div class="panel-body">
            <div class="form-group">
                <?php echo $this->formLabel($form->get('name')) ?>
                <?php echo $this->formText($form->get('name')->setAttribute('class', 'form-control')) ?>
                <?php echo $this->formElementErrors($form->get('name')) ?>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon wb-check"></i>
                <span><?php echo $this->escapeHtml($this->translate("Save")); ?></span>
            </button>
            <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current()]) ?>" class="btn btn btn-danger">
                <i class="icon wb-close"></i>
                <span><?php echo $this->escapeHtml($this->translate("Cancel")); ?></span>
            </a>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form) ?>
</div>