<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
$this->headTitle()->append($this->translate('Edit stadium'))
    ->append($this->translate('Stadiums'))
    ->append($this->translate('Soccer'));

$this->headLink()
    ->appendStylesheet(
        $this->basePath('assets/admin/vendor/select2/select2.min.css')
    );

$this->inlineScript()
    ->appendFile($this->basePath('assets/admin/vendor/select2/select2.min.js'))
    ->appendFile($this->basePath('assets/admin/js/components/select2.min.js'));

$this->formElementErrors()->setMessageOpenFormat(
    '<ul class="list-group text-danger">
                <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
)->setMessageSeparatorString(
    '</li>
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
);
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Edit stadium') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $this->url(null, ['action' => 'index', 'id' => null], true) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>">
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <?php echo $this->form()->openTag($form); ?>
    <div class="panel panel-bordered">
        <div class="panel-body">
            <fieldset>
                <legend class="margin-0"><?php echo $this->formLabel($form->get('name')) ?></legend>
                <div class="row">
                    <?php foreach ($form->get('name') as $name => $subElement): ?>
                        <div class="col-md-3 col-sm-6">
                            <h5><?php echo $this->formLabel($subElement) ?></h5>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="flag-icon flag-icon<?php echo substr($name, strrpos($name, '-'))?>"></i>
                                    </span>
                                    <?php
                                    echo $this->formText(
                                        $subElement->setAttribute('class', 'form-control')
                                            ->setAttribute('name', sprintf('%s[%s]', $form->get('name')->getName(), $name))
                                    );
                                    ?>
                                </div>
                                <?php echo $this->formElementErrors($subElement); ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </fieldset>
            <fieldset>
                <legend class="margin-0"><?php echo $this->formLabel($form->get('located')) ?></legend>
                <div class="row">
                    <?php foreach ($form->get('located') as $name => $subElement): ?>
                        <div class="col-md-3 col-sm-6">
                            <h5><?php echo $this->formLabel($subElement) ?></h5>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="flag-icon flag-icon<?php echo substr($name, strrpos($name, '-'))?>"></i>
                                    </span>
                                    <?php
                                    echo $this->formText(
                                        $subElement->setAttribute('class', 'form-control')
                                            ->setAttribute('name', sprintf('%s[%s]', $form->get('located')->getName(), $name))
                                    );
                                    ?>
                                </div>
                                <?php echo $this->formElementErrors($subElement); ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </fieldset>
            <div class="form-group">
                <?php
                $form->get('owner')
                    ->setAttribute('data-plugin', 'select2')
                    ->setAttribute('id', 'stadium-owner-club');

                echo $this->formLabel($form->get('owner')),
                $this->formSelect($form->get('owner')),
                $this->formElementErrors($form->get('owner'))
                ?>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-success">
                <i class="icon wb-plus"></i>
                <span><?php echo $this->escapeHtml($this->translate("Save")); ?></span>
            </button>
            <a href="<?php echo $this->url(null, ['action' => 'index', 'id' => null], true) ?>" class="btn btn btn-danger">
                <i class="icon wb-close"></i>
                <span><?php echo $this->escapeHtml($this->translate("Cancel")); ?></span>
            </a>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form) ?>
</div>