<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Soccer\Form\CommentMatchEventForm $form
 */

$form->setAttribute('action', $this->url(null, [], true));

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <div class="row">
            <div class="col-xs-4">
                <?php
                echo $this->formLabel($form->get('minutes')->setAttribute('id', 'mec-minutes')),
                $this->formText($form->get('minutes')->setAttribute('class', 'form-control')),
                $this->formElementErrors($form->get('minutes'))
                ?>
            </div>
            <div class="col-xs-4">
                <?php
                echo $this->formLabel($form->get('seconds')->setAttribute('id', 'mec-seconds')),
                $this->formText($form->get('seconds')->setAttribute('class', 'form-control')),
                $this->formElementErrors($form->get('seconds'))
                ?>
            </div>
            <div class="col-xs-4">
                <?php
                echo $this->formLabel($form->get('extra')->setAttribute('id', 'mec-extra')),
                $this->formText($form->get('extra')->setAttribute('class', 'form-control')),
                $this->formElementErrors($form->get('extra'))
                ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?php
            echo $this->formLabel($form->get('locale')->setAttribute('id', 'mec-locale')),
                $this->formSelect($form->get('locale')->setAttribute('class', 'form-control')),
                $this->formElementErrors($form->get('locale'))
        ?>
    </div>
    <div class="form-group">
        <?php
            echo $this->formLabel($form->get('text')->setAttribute('id', 'mec-text')),
            $this->formTextarea($form->get('text')->setAttribute('class', 'form-control')->setAttribute('data-plugin', 'ckeditor')),
            $this->formElementErrors($form->get('text'))
        ?>
    </div>
    <div class="form-group">
        <button class="btn btn-primary"><?php echo $this->translate('Send') ?></button>
    </div>
<?php echo $this->form()->closeTag($form) ?>
