<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Articles\Module'                                 => __DIR__ . '/Module.php',
    'Articles\Controller\ArticlesController'          => __DIR__ . '/src/Articles/Controller/ArticlesController.php',
    'Articles\Controller\Manage\ArticlesController'   => __DIR__ . '/src/Articles/Controller/Manage/ArticlesController.php',
    'Articles\Controller\Manage\CategoriesController' => __DIR__ . '/src/Articles/Controller/Manage/CategoriesController.php',
    'Articles\Entity\Article'                         => __DIR__ . '/src/Articles/Entity/Article.php',
    'Articles\Entity\Category'                        => __DIR__ . '/src/Articles/Entity/Category.php',
    'Articles\Form\ArticlesForm'                      => __DIR__ . '/src/Articles/Form/ArticlesForm.php',
    'Articles\Form\CategoriesForm'                    => __DIR__ . '/src/Articles/Form/CategoriesForm.php',
    'Articles\Repository\ArticlesRepository'          => __DIR__ . '/src/Articles/Repository/ArticlesRepository.php',
    'Articles\Repository\CategoriesRepository'        => __DIR__ . '/src/Articles/Repository/CategoriesRepository.php',
    'Articles\View\Helper\ArticlesHelper'             => __DIR__ . '/src/Articles/View/Helper/ArticlesHelper.php',
    'Articles\View\Helper\RelatedHelper'              => __DIR__ . '/src/Articles/View/Helper/RelatedHelper.php',
);
