<div class="modal fade in" style="display: block; padding-right: 17px;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="panel-group panel-group-continuous margin-0" id="actions-acc" aria-multiselectable="true" role="tablist">
                <?php foreach ($actions as $key => $action): ?>
                    <div class="panel">
                        <div class="panel-heading">
                            <a class="panel-title <?php echo $key ? '': 'collapsed' ?>" aria-expanded="<?php echo !$key ? 'true': 'false' ?>" data-parent="#actions-acc" data-toggle="collapse" href="#<?php echo md5($action->getTitle()) ?>"> 
                                <?php echo $this->translate($action->getTitle()) ?>
                            </a>
                        </div>
                        <div id="<?php echo md5($action->getTitle()) ?>" class="panel-collapse collapse <?php echo $key ? '': 'in' ?>">
                            <div class="panel-body">
                                <ul class="list-group">
                                    <?php if ($action instanceof \Menu\Actions\AbstractActionsContainer): ?>
                                        <?php foreach ($action->getActions() as $subAction): ?>
                                        <li class="list-group-item">
                                            <a href="<?php echo $this->url($subAction->getRouteName(), $subAction->getRouteParams(), $subAction->getRouteOptions(), true) ?>"><?php echo $this->translate($subAction->getTitle()) ?></a>
                                        </li>
                                        <?php endforeach ?>
                                    <?php else: ?>
                                        <li class="list-group-item">
                                            <a href="<?php echo $this->url($action->getRouteName(), $action->getRouteParams(), $action->getRouteOptions(), true) ?>"><?php echo $this->translate($action->getTitle()) ?></a>
                                        </li>
                                    <?php endif ?>
                                </ul>
                            </div>
                        </div>
                    </div>                    
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>