<?php
$this->headTitle()->append($this->translate('Clubs'))
    ->append($this->translate('Soccer'));

$this->headLink()
    ->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-table/bootstrap-table.css')
    );

$this->headStyle()
    ->appendStyle(
        "
            .table > tbody > tr > td, .table > tbody > tr > th,
            .table > tfoot > tr > td, .table > tfoot > tr > th,
            .table > thead > tr > td, .table > thead > tr > th {
                vertical-align: middle;
            }
        "
    );

$this->inlineScript()
    ->appendFile(
        $this->basePath('assets/admin/vendor/bootstrap-table/bootstrap-table.min.js')
    )
    ->appendFile(
        $this->basePath('assets/admin/vendor/bootstrap-table/extensions/mobile/bootstrap-table-mobile.js')
    );
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Clubs') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $this->url(null, ['action' => 'add'], true) ?>" class="btn btn-primary">
            <i class="icon wb-plus" aria-hidden="true"></i>
            <span><?php echo $this->escapeHtml($this->translate("Add new")); ?></span>
        </a>
    </div>
</div>
<div class="page-content">
    <?php if ($clubs->getCurrentItemCount()): ?>
        <div class="panel">
            <div class="panel-body">
                <div class="table-responsive">
                    <table id="staff"></table>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="well text-center">
            <h1>
                <i class="icon wb-inbox"></i>
            </h1>
            <h3>
                <span><?php echo $this->translate('There is no any clubs.') ?></span>
            </h3>
        </div>
    <?php endif; ?>
</div>
<div style="display:none;">
    <div id="colactions">
        <a href="<?php echo $this->url(null, ['action' => 'edit', 'id' => ':id'], true) ?>" class="btn btn-default btn-sm btn-inverse btn-icon" title="<?php echo $this->translate("Edit") ?>">
            <i class="icon wb-settings"></i>
        </a>
        <a href="<?php echo $this->url(null, ['action' => 'players', 'id' => ':id'], true) ?>" class="btn btn-default btn-sm btn-inverse btn-icon" title="<?php echo $this->translate("Edit players") ?>">
            <i class="icon wb-users"></i>
        </a>
        <a href="<?php echo $this->url(null, ['action' => 'delete', 'id' => ':id'], true) ?>" class="btn btn-default btn-sm btn-inverse btn-icon" title="<?php echo $this->translate("Delete") ?>">
            <i class="icon wb-trash text-danger"></i>
        </a>
    </div>
    <div id="collogo">
        <img src="<?php echo $this->basePath(':image') ?>" class="img-responsive">
    </div>
    <div id="colparentClub">
        <div class="text-center">
            <p>:name</p>
            <img src="<?php echo $this->basePath(':image') ?>" alt=":name" class="img-responsive center-block">
        </div>
    </div>
</div>
<?php
$this->inlineScript()
    ->captureStart();
?>
/*<script>*/
    replaceAll = function (key, value, text) {
        if (typeof this === 'string' && !text) {
            text = this;
        }

        while (text.indexOf(key) > -1) {
            text = text.replace(key, value);
        }

        return text;
    };
    // Js core overwrite
    String.prototype.replaceAll = replaceAll;

    jQuery.fn.bootstrapTable.columnDefaults.formatter = function (value, row, index) {
        switch (this.field) {
            case 'actions':
                return replaceAll(':id', row.id, $('#colactions').html());
            case 'logo':
                return replaceAll(':image', row.logo, $('#collogo').html());
            case 'parentClub':
                if (typeof row.parentClub == 'object' && row.parentClub.name && row.parentClub.logo) {
                    return replaceAll(':name', row.parentClub.name["<?php echo $this->locale()->current() ?>"], replaceAll(':image', row.parentClub.logo, $('#colparentClub').html()));
                } else {
                    return '-';
                }
            case 'tableName':
            case 'name':
                var col = '';

                for (var i in row[this.field]) {
                    col += '<p><i class="flag-icon flag-icon'+i.substring(i.lastIndexOf('-'))+'"></i>&nbsp;'+row[this.field][i]+'</p>';
                }

                return col;
            default:
                return value;
        }
    };

    $('table#staff').bootstrapTable({
        url: "<?php echo $this->escapeJs($this->url(null, [], true)) ?>",
        striped: true,
        search: true,
        pagination: true,
        showRefresh: true,
        showToggle: true,
        showColumns: true,
        iconSize: 'outline',
        sidePagination: 'server',
        icons: {
            refresh: 'wb-refresh',
            toggle: 'wb-order',
            columns: 'wb-list-bulleted'
        },
        columns: [
            {
                'field': 'logo',
                'title': "<?php echo $this->escapeJs($this->translate("Logo")); ?>"
            },
            {
                'field': 'alias',
                'title': "<?php echo $this->escapeJs($this->translate("Alias")); ?>",
                'sortable': true,
            },
            {
                'field': 'name',
                'title': "<?php echo $this->escapeJs($this->translate("Name")); ?>",
                'sortable': false,
            },
            {
                'field': 'tableName',
                'title': "<?php echo $this->escapeJs($this->translate("Result and fixtures name")); ?>",
                'sortable': false,
            },
            {
                'field': 'founded',
                'title': "<?php echo $this->escapeJs($this->translate("Founded")); ?>",
                'sortable': true,
            },
            {
                'field': 'parentClub',
                'title': "<?php echo $this->escapeJs($this->translate("Farm club of")); ?>",
                'sortable': false,
            },
            {
                'field': 'actions',
                'title': "<?php echo $this->escapeJs($this->translate("Actions")); ?>",
            }
        ],
    });
    /*</script>*/
<?php $this->inlineScript()->captureEnd(); ?>
