<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Soccer\Module'                        => __DIR__ . '/Module.php',
    'Soccer\Controller\SkeletonController' => __DIR__ . '/src/Soccer/Controller/SkeletonController.php',
    'ZendSkeletonModuleTest\Framework\TestCase'        => __DIR__ . '/tests/Soccer/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'                => __DIR__ . '/tests/Soccer/SampleTest.php',
);