<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
$this->headTitle()->append($this->translate('Add'))
    ->append($this->translate('Seasons'))
    ->append($this->translate('Tournaments'))
    ->append($this->translate('Soccer'));

$this->headLink()
    ->appendStylesheet(
            $this->basePath('assets/admin/vendor/multi-select/multi-select.css')
    )
    ->appendStylesheet(
        $this->basePath('assets/admin/css/../fonts/material-design/material-design.css')
    )
    ->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-touchspin/bootstrap-touchspin.css')
    );

$this->inlineScript()
    ->appendFile($this->basePath('assets/admin/vendor/multi-select/jquery.multi-select.js'))
    ->appendFile($this->basePath('assets/admin/js/components/multi-select.js'))
    ->appendFile($this->basePath('assets/admin/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js'))
    ->appendFile($this->basePath('assets/admin/js/components/bootstrap-touchspin.js'));

$this->headStyle()
    ->appendStyle(
        "
            .form-group.disabled {
                opacity: 0.5;
                cursor: not-allowed;
            }
            
            #matches-group > .ms-container {
                width: 100%;
            }
            
            #matches-group .ms-list {
                min-height: 320px;
            }
        "
    );

$this->formElementErrors()->setMessageOpenFormat(
    '<ul class="list-group text-danger">
                <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
)->setMessageSeparatorString(
    '</li>
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
);
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('New season') ?></h1>
    <ol class="breadcrumb">
        <li>
            <a href="<?php echo $this->url('app/admin/soccer/tournaments', ['action' => 'index'], true) ?>"><?php echo $this->translate('Tournaments') ?></a>
        </li>
        <li>
            <a href="<?php echo $this->url(null, ['action' => 'index'], true) ?>"><?php echo $tournament->getLabel($this->locale()->current()) ?></a>
        </li>
        <li class="active"><?php echo $this->translate('New season') ?></li>
    </ol>
    <div class="page-header-actions">
        <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current(), 'tournament' => $tournament->getId()]) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>">
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel">
        <div class="panel-body">
            <fieldset>
                <legend class="margin-0"><?php echo $this->formLabel($form->get('label')) ?></legend>
                <div class="row">
                    <?php foreach ($form->get('label') as $name => $subElement): ?>
                        <div class="col-md-3 col-sm-6">
                            <h5><?php echo $this->formLabel($subElement) ?></h5>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="flag-icon flag-icon<?php echo substr($name, strrpos($name, '-'))?>"></i>
                                    </span>
                                    <?php
                                    echo $this->formText(
                                        $subElement->setAttribute('class', 'form-control')
                                            ->setAttribute('name', sprintf('%s[%s]', $form->get('label')->getName(), $name))
                                    );
                                    ?>
                                </div>
                                <?php echo $this->formElementErrors($subElement); ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </fieldset>
            <div class="form-group" id="matches-group">
                <h5><?php echo $this->formLabel($form->get('clubs')->setAttribute('id', 'matches')) ?></h5>
                <?php
                echo $this->formSelect(
                    $form->get('clubs')
                        ->setAttribute('class', 'form-control')
                        ->setAttribute('data-plugin', 'multiSelect')
                );
                ?>
                <?php echo $this->formElementErrors($form->get('clubs')); ?>
            </div>
            <div class="form-group">
                <h5><?php echo $this->formLabel($form->get('type')) ?></h5>
                <?php
                echo $this->formSelect(
                    $form->get('type')
                        ->setAttribute('class', 'form-control')
                );
                ?>
                <?php echo $this->formElementErrors($form->get('type')); ?>
            </div>
            <div class="form-group additional-options" id="winsBy" style="display: none;">
                <h5><?php echo $this->formLabel($form->get('winsBy')) ?></h5>
                <?php
                echo $this->formSelect(
                    $form->get('winsBy')
                        ->setAttribute('class', 'form-control')
                );
                ?>
                <?php echo $this->formElementErrors($form->get('winsBy')); ?>
            </div>
            <div class="checkbox-custom checkbox-primary" style="margin-bottom: 15px;">
                <?php echo $this->formCheckbox(
                    $form->get('visible')
                    ->setAttribute('id', 'visibility')
                    ->setOption('label_attributes', ['for' => 'visibility'])
                ) ?>
                <?php echo $this->formLabel($form->get('visible')) ?>
                <?php echo $this->formElementErrors($form->get('visible')) ?>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-raised">
                    <i class="icon md-check"></i>
                    <span><?php echo $this->translate('Add') ?></span>
                </button>
                <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current(), 'tournament' => $tournament->getId()]) ?>" class="btn btn-raised btn-danger">
                    <i class="icon md-close"></i>
                    <?php echo $this->translate('Cancel') ?>
                </a>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form) ?>
</div>
<?php $this->inlineScript()->captureStart(); ?>
    // Season type options
    (function ($) {
        var leagueSelected = function () {
            $('#winsBy').fadeIn(400);
        };

        $('#type select.form-control').change(
            function () {
                var $this = $(this);

                if (!$this.val().trim()) {
                    return;
                }

                $('.additional-options').fadeOut(400);

                if ($this.val().trim() == "<?php echo \Soccer\Entity\Season::TYPE_LEAGUE ?>") {
                    leagueSelected.apply(this);
                }
            }
        ).trigger('change');
    })(jQuery);
<?php $this->inlineScript()->captureEnd(); ?>