<?php $this->headTitle()->append($this->translate('Profile')) ?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Profile') ?></h1>
</div>
<div class="page-content">
    <!-- Panel X-Editable -->    
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('User profile settings') ?></h3>
        </div>
        <div class="panel-body">
            <?php  
                $form->setAttribute('action', $this->url(null, ['locale' => $this->locale()->current()]))
            ?>
            <?php echo $this->form()->openTag($form) ?>
                <div class="form-group">
                    <h5>
                        <?php echo $this->formLabel($form->get('name')) ?>
                    </h5>
                    <?php 
                        echo $this->formText(
                            $form->get('name')
                            ->setAttribute('class', 'form-control')
                        )
                    ?>
                </div>
                <div class="form-group">
                    <h5>
                        <?php echo $this->formLabel($form->get('password')) ?>
                    </h5>
                    <?php 
                        echo $this->formPassword(
                            $form->get('password')
                            ->setAttribute('class', 'form-control')
                        )
                    ?>
                    <p class="help-block">
                        <?php echo $this->translate('Do not touch this field, unless you want to change your password!') ?>
                    </p>
                </div>
                <div class="form-group">
                    <h5>
                        <?php echo $this->formLabel($form->get('password_check')) ?>
                    </h5>
                    <?php 
                        echo $this->formPassword(
                            $form->get('password_check')
                            ->setAttribute('class', 'form-control')
                        )
                    ?>
                    <p class="help-block">
                        <?php echo $this->translate('This field value must be identical with password field') ?>
                    </p>
                </div>
                <button type="submit" class="btn btn-raised btn-primary">
                    <?php echo $this->translate('Save changes') ?>
                </button>
            <?php echo $this->form()->closeTag($form) ?>
        </div>
    </div>
    <!-- End Panel X-Editable --> 
</div>