<?php
$this->headTitle()
    ->append($group->getName())
    ->append($this->translate('Staff'));
?>

<div class="section subbanner">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="caption">
                    <?php echo $group->getName() ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section singlepage">
    <div class="container">
        <div class="row pbot-main">
            <div class="col-sm-12 col-md-12">
                <div class="row">
                    <?php if ($group->getMembers()->count()): ?>
                        <?php foreach ($group->getMembers() as $member): ?>
                            <div class="col-sm-12 col-md-4">
                                <div class="shop-item">
                                    <div class="gambar">
                                        <?php if ($member->getPhoto()) : ?>
                                            <img src="<?php echo $this->basePath($member->getPhoto()) ?>" alt="" class="img-responsive">
                                        <?php else : ?>
                                            <img src="<?php echo $this->basePath('img/logo_transparent_20.png') ?>" alt="" class="img-responsive">
                                        <?php endif; ?>
                                    </div>
                                    <div class="item-body">
                                        <div class="name">
                                            <?php echo $member->getFirstname() ?>
                                            <b><?php echo $member->getLastname() ?></b>
                                        </div>

                                        <div class="name">
                                            <span><?php echo $this->escapeHtml($this->translate("Position")); ?></span>:
                                            <span class="pull-right"><?php echo $member->getPosition() ?></span>
                                        </div>

                                        <div class="name">
                                            <span><?php echo $this->escapeHtml($this->translate("In club since")); ?></span>:
                                            <span class="pull-right"><?php echo $member->getInClubSince() ?>, <?php echo $this->escapeHtml(sprintf($this->translate("%s year(s)"), date('Y') - $member->getInClubSince())); ?></span>
                                        </div>

                                        <div class="name">
                                            <span><?php echo $this->escapeHtml($this->translate("Birth date")); ?></span>:
                                            <span class="pull-right text-capitalize"><?php echo $this->translate(strtolower($member->getBirthDate()->format('F'))),$member->getBirthDate()->format(' d, Y')  ?></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="well text-center">
                            <h1><i class="icon md-inbox"></i></h1>
                            <h3><?php echo $this->translate('Content will be added soon') ?></h3>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
