<?php  
    $this->headTitle()
    ->append($this->translate('Create folder'))
    ->append($this->translate('Images manager'));

    $form->setAttribute('action', $this->serverUrl(true))->prepare();
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Create folder') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $back ?>" class="btn btn-sm btn-inverse btn-round"> 
            <i aria-hidden="true" class="icon wb-arrow-left"></i>
            <span class="hidden-xs"><?php echo $this->translate('Return to manager') ?></span>
        </a>
    </div>
</div>
<div class="page-content">
    <div class="panel">
        <div class="panel-body container-fluid">
            <div>
                <?php echo $this->form()->openTag($form) ?>
                    <div class="form-group">
                        <h4><?php echo $this->translate($form->get('name')->getLabel()) ?></h4>
                        <?php  
                            echo $this->formText(
                                $form->get('name')
                                ->setAttribute('class', 'form-control focus')
                                ->setAttribute('autofocus', true)
                                ->setValue('New_folder')
                            );
                            echo $this->formElementErrors($form->get('name'));
                        ?>
                    </div>
                    <button type="submit" class="btn btn-success">
                        <i class="icon wb-check"></i>
                        <span><?php echo $this->translate('Save') ?></span>
                    </button>
                    <a class="btn btn-danger" href="<?php echo $back ?>">
                        <i class="icon wb-close"></i>
                        <span><?php echo $this->translate('Cancel') ?></span>
                    </a>
                <?php echo $this->form()->closeTag($form) ?>
            </div>
        </div>
    </div>
</div>