<?php  
    $this->headTitle()
    ->append($this->translate('Delete folder'))
    ->append($this->translate('Images manager'));
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Delete folder') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $back ?>" class="btn btn-sm btn-inverse btn-round"> 
            <i aria-hidden="true" class="icon wb-arrow-left"></i>
            <span class="hidden-xs"><?php echo $this->translate('Return to manager') ?></span>
        </a>
    </div>
</div>
<div class="page-content">
    <div class="panel">
        <div class="panel-body container-fluid">
            <h4>
                <?php 
                    printf(
                        $this->translate("Folder '%s' will be deleted process?"),
                        $folder
                    )
                ?>
            </h4>
            <?php if ($messages): ?>
                <ul>
                    <?php foreach ($messages as $message): ?>
                        <li><?php echo $message ?></li>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>
        </div>
        <div class="panel-footer">
            <a class="btn btn-danger" href="<?php echo $confirm ?>">
                <i class="icon wb-trash"></i>
                <span><?php echo $this->translate('Yes') ?></span>
            </a>
            <a class="btn btn-warning" href="<?php echo $back ?>">
                <i class="icon wb-close"></i>
                <span><?php echo $this->translate('No') ?></span>
            </a>            
        </div>
    </div>
</div>