<?php  
    $this->headTitle()->append($this->translate('Images upload'));
    $this->headLink()->appendStylesheet($this->basePath('assets/admin/vendor/blueimp-file-upload/jquery.fileupload.css'));
    $this->headStyle()->appendStyle(
        "
            .preview.vertical-align > img {
                height: auto;
                width: 100%;
            }
        "
    );
?>
<div class="page-header">
    <h1 class="page-title margin-bottom-10"><?php echo $this->translate('Images upload') ?></h1>
    <p><?php printf($this->translate('Current folder: %s'), '/'.$this->path) ?></p>
    <div class="page-header-actions">
        <a href="<?php echo $back ?>" class="btn btn-sm btn-icon btn-inverse btn-round"> 
            <i aria-hidden="true" class="icon wb-arrow-left"></i>
            <span><?php echo $this->translate('Return to images manager') ?></span>
        </a>
    </div>
</div>
<div class="page-content">
    <form class="upload-form" id="exampleUploadForm" method="POST">
        <input type="file" id="inputUpload" name="images[]" multiple="" />
        <div class="uploader-inline">
            <h3 class="upload-instructions">
                <i class="icon wb-upload" style="font-size: 1.5em;"></i>
                <br>
                <span><?php echo $this->translate('Click Or Drop Files To Upload') ?></span>
            </h3>
        </div>
        <div class="file-wrap container-fluid">
            <div class="file-list row"></div>
            <div class="clearfix"></div>
        </div>
    </form>
</div>
<?php  
    $this->inlineScript()
    ->appendFile($this->basePath('assets/admin/vendor/jquery-ui/jquery-ui.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-tmpl/tmpl.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-canvas-to-blob/canvas-to-blob.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-load-image/load-image.all.min.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-file-upload/jquery.fileupload.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-file-upload/jquery.fileupload-process.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-file-upload/jquery.fileupload-image.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-file-upload/jquery.fileupload-validate.js'))
    ->appendFile($this->basePath('assets/admin/vendor/blueimp-file-upload/jquery.fileupload-ui.js'));

    $this->inlineScript()
    ->appendScript(
        '
            (function(document, window, $) {
              $(document).ready(function($) {
                Site.run();
              });

              // Example File Upload
              // -------------------
              $(\'#exampleUploadForm\').fileupload({
                url: \''.$this->escapeJs($this->serverUrl(true)).'\',
                dropzone: $(\'#exampleUploadForm\'),
                filesContainer: $(\'.file-list\'),
                uploadTemplateId: false,
                downloadTemplateId: false,
                sequentialUploads: true,
                limitMultiFileUploads: 1,
                maxFileSize: 1572864,
                autoUpload: true,
                uploadTemplate: tmpl(
                  \'{% for (var i=0, file; file=o.files[i]; i++) { %}\' +
                  \'<div class="file template-upload fade col-lg-2 col-md-4 col-sm-6 {%=file.type.search("image") !== -1? "image" : "other-file"%}">\' +
                  \'<div class="file-item">\' +
                  \'<div class="preview vertical-align">\' +
                  \'<div class="file-action-wrap">\' +
                  \'<div class="file-action">\' +
                  \'{% if (!i && !o.options.autoUpload) { %}\' +
                  \'<i class="icon wb-upload start" data-toggle="tooltip" data-original-title="Upload file" aria-hidden="true"></i>\' +
                  \'{% } %}\' +
                  \'{% if (!i) { %}\' +
                  \'<i class="icon wb-close cancel" data-toggle="tooltip" data-original-title="Stop upload file" aria-hidden="true"></i>\' +
                  \'{% } %}\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'<div class="info-wrap">\' +
                  \'<div class="title">{%=file.name%}</div>\' +
                  \'</div>\' +
                  \'<div class="progress progress-striped active" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" role="progressbar">\' +
                  \'<div class="progress-bar progress-bar-success" style="width:0%;"></div>\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'{% } %}\'
                ),
                downloadTemplate: tmpl(
                  \'{% for (var i=0, file; file=o.files[i]; i++) { %}\' +
                  \'<div class="file template-download fade col-lg-2 col-md-4 col-sm-6 {%=file.type.search("image") !== -1? "image" : "other-file"%}">\' +
                  \'<div class="file-item">\' +
                  \'<div class="preview vertical-align">\' +
                  \'<div class="file-action-wrap">\' +
                  \'<div class="file-action" data-delete-url="{%=file.deleteUrl%}">\' +
                  \'<i class="icon wb-trash delete" data-toggle="tooltip" data-original-title="Delete files" aria-hidden="true"></i>\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'<img src="{%=file.thumbnailUrl%}"/>\' +
                  \'</div>\' +
                  \'<div class="info-wrap">\' +
                  \'<div class="title">{%=file.name%}</div>\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'</div>\' +
                  \'{% } %}\'
                ),
                forceResize: true,
                previewCanvas: false,
                previewMaxWidth: false,
                previewMaxHeight: false,
                previewThumbnail: true
              }).on(\'fileuploadprocessalways\', function(e, data) {
                var length = data.files.length;

                for (var i = 0; i < length; i++) {
                  if (!data.files[i].type.match(
                      /^image\/(gif|jpeg|png|svg\+xml)$/)) {
                    data.files[i].filetype = \'other-file\';
                  } else {
                    data.files[i].filetype = \'image\';
                  }
                }
              }).on(\'fileuploadadded\', function(e) {
                var $this = $(e.target);

                if ($this.find(\'.file\').length > 0) {
                  $this.addClass(\'has-file\');
                } else {
                  $this.removeClass(\'has-file\');
                }
              }).on(\'fileuploadfinished\', function(e) {
                var $this = $(e.target);

                if ($this.find(\'.file\').length > 0) {
                  $this.addClass(\'has-file\');
                } else {
                  $this.removeClass(\'has-file\');
                }
              }).on(\'fileuploaddestroy\', function(e, data) {
                $.get(data.context.find(".file-action").data("delete-url"));
              }).on(\'fileuploaddestroyed\', function(e) {
                var $this = $(e.target);

                if ($this.find(\'.file\').length > 0) {
                  $this.addClass(\'has-file\');
                } else {
                  $this.removeClass(\'has-file\');
                }
              }).on(\'click\', function(e) {
                if ($(e.target).parents(\'.file\').length === 0) $(\'#inputUpload\')
                  .trigger(\'click\');
              });

              $(document).bind(\'dragover\', function(e) {
                var dropZone = $(\'#exampleUploadForm\'),
                  timeout = window.dropZoneTimeout;
                if (!timeout) {
                  dropZone.addClass(\'in\');
                } else {
                  clearTimeout(timeout);
                }
                var found = false,
                  node = e.target;
                do {
                  if (node === dropZone[0]) {
                    found = true;
                    break;
                  }
                  node = node.parentNode;
                } while (node !== null);
                if (found) {
                  dropZone.addClass(\'hover\');
                } else {
                  dropZone.removeClass(\'hover\');
                }
                window.dropZoneTimeout = setTimeout(function() {
                  window.dropZoneTimeout = null;
                  dropZone.removeClass(\'in hover\');
                }, 100);
              });

              $(\'#inputUpload\').on(\'click\', function(e) {
                e.stopPropagation();
              });

              $(\'#uploadlink\').on(\'click\', function(e) {
                e.stopPropagation();
              });
            })(document, window, jQuery);
        '
    );
?>