<?php  
    $this->headTitle()->append($this->translate('Create new category'));

    $form->setAttribute(
        'action', 
        $this->url(
            null, 
            [
                'locale' => $this->locale()->current(), 
                'action' => 'add'
            ]
        )
    )->prepare();

    $this->formElementErrors()->setMessageOpenFormat(
        '<ul class="list-group text-danger">
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                <i class="icon wb-alert" aria-hidden="true"></i>'
    )->setMessageSeparatorString(
        '</li>
        <li class="list-group-item padding-0" style="padding-left:10px !important;">
                <i class="icon wb-alert" aria-hidden="true"></i>'
    );
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('New category') ?></h1>
<div class="page-header-actions">
    <a href="<?php echo $this->url('app/admin/articles/categories', ['locale' => $this->locale()->current()]) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>"> 
        <i class="icon wb-close" aria-hidden="true"></i>
    </a>
</div>
</div>
<div class="page-content">
    <div class="panel">
        <div class="panel-body container-fluid">
            <?php echo $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group <?php $form->get('title')->getMessages() ? 'has-error': '' ?>">
                        <?php  
                            echo 
                            $this->formLabel($form->get('title')),
                            $this->formText(
                                $form->get('title')
                                ->setAttribute('class', 'form-control')
                            ),
                            $this->formElementErrors($form->get('title'))
                        ?>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group <?php $form->get('locale')->getMessages() ? 'has-error': '' ?>">
                        <?php  
                            echo 
                            $this->formLabel($form->get('locale')),
                            $this->formSelect(
                                $form->get('locale')
                                ->setAttribute('class', 'form-control')
                            ),
                            $this->formElementErrors($form->get('locale'))
                        ?>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success">
                <i class="icon wb-check"></i>
                <span><?php echo $this->translate('Create') ?></span>
            </button>
            <?php echo $this->form()->closeTag($form) ?>
        </div>
    </div>
</div>