<?php 
    $this->headTitle()->append($this->translate('Categories'));

    $this->headLink()->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-select/bootstrap-select.css')
    )->appendStylesheet(
        $this->basePath('assets/admin/css/apps/documents.css')
    );
?>
<div class="page-header">
    <h1 class="page-title margin-bottom-10">Category List</h1>
    <div class="page-header-actions">
        <a href="<?php echo $this->url('app/admin/articles/categories', ['locale' => $this->locale()->current(), 'action' => 'add']) ?>" class="btn btn-primary"> 
        <i class="icon wb-plus" aria-hidden="true"></i>
            <span class="hidden-xs"><?php echo $this->translate('Create') ?></span>
        </a>
    </div>
</div>
<div class="page-content">
    <div class="documents-wrap categories">
        <?php if ($categories): ?>
            <?php $locales = $this->locale()->all(); ?>
        <ul class="blocks blocks-100 blocks-xlg-4 blocks-md-3 blocks-xs-2" data-plugin="matchHeight">
            <?php foreach ($categories as $category): ?>
                <li style="height: 250px;">
                    <div class="category">
                        <div style="margin-bottom: 5px;">
                            <div class="pull-right">
                                <div class="dropdown">
                                    <span class="icon wb-more-vertical dropdown-toggle" data-toggle="dropdown" aria-expanded="false" role="button"></span>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="<?php echo $this->url('app/admin/articles/categories', ['locale' => $this->locale()->current(), 'action' => 'edit', 'id' => $category->getUri(), 'targetLocale' => $category->getLocale()]) ?>" title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>">
                                                <i class="icon wb-edit"></i>
                                                <span><?php echo $this->translate('Edit') ?></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('app/admin/articles/categories', ['locale' => $this->locale()->current(), 'action' => 'delete', 'id' => $category->getUri(), 'targetLocale' => $category->getLocale()]) ?>" title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>">
                                                <i class="icon wb-trash"></i>
                                                <span><?php echo $this->translate('Delete') ?></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="icon-wrap"> 
                            <i class="icon wb-desktop" aria-hidden="true"></i>
                        </div>
                        <h4><?php echo $category->getTitle() ?></h4>
                        <?php if (isset($locales[$category->getLocale()])): ?>
                            <p>
                                <i class="flag-icon flag-icon-<?php echo strtolower(substr($category->getLocale(), strrpos($category->getLocale(), '-') + 1)) ?>"></i>
                                <span><?php echo $locales[$category->getLocale()] ?></span>
                            </p>
                        <?php endif ?>
                        <?php if (count($category->getArticles())): ?>
                            <a href="<?php echo $this->url('app/admin/articles/articles', ['locale' => $this->locale()->current()], ['query' => ['category' => $category->getId()]]) ?>"><?php printf($this->translate('%s articles'), count($category->getArticles())) ?></a>
                        <?php else: ?>
                            <p><?php printf($this->translate('%s articles'), 0) ?></p>
                        <?php endif ?>
                    </div>
                </li>                
            <?php endforeach ?>
        </ul>
        <?php else: ?>
        <div class="well well-inverse">
            <h1 class="text-center">
                <i class="icon wb-inbox"></i>
            </h1>
            <h4 class="text-center"><?php echo $this->translate('Categories are not added yet!') ?></h4>
        </div>
        <?php endif ?>
    </div>
</div>
<?php  
    $this->inlineScript()->appendFile(
        $this->basePath('assets/admin/js/apps/app.js')
    )->appendFile(
        $this->basePath('assets/admin/js/apps/documents.js')
    );
?>