<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
echo $this->doctype();
?>
<html class="no-js" lang="<?php echo substr($this->locale()->current(), 0, 2) ?>">
<head>
    <base href="<?php echo $this->basePath('/') ?>">
    <meta charset="UTF-8">
    <?php
        echo $this->headTitle($this->translate('Title name'))
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- ==============================================
    CSS
    =============================================== -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('qizilqum/css/bootstrap.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('qizilqum/css/font-awesome.min.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('qizilqum/css/owl.carousel.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('qizilqum/css/owl.theme.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('qizilqum/css/magnific-popup.css') ?>" />
    <!-- ==============================================
    Google Fonts
    =============================================== -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <!-- ==============================================
    Custom Stylesheet
    =============================================== -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('qizilqum/css/style.css') ?>" />
    <?php
        echo $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath('qizilqum/images/favicon.png'),
        ]);
    ?>
    <script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/modernizr.min.js') ?>"></script>
</head>
<body>
<!-- Load page -->
<!--div class="animationload">
    <div class="loader"></div>
</div-->

<!-- NAVBAR SECTION -->
<div class="navbar navbar-main navbar-fixed-top">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
                    <?php if (count($this->locale()->all()) > 1) : ?>
                        <div class="top-sosmed pull-right">
                            <div class="dropdown">
                                <a
                                    class="dropdown-toggle"
                                    type="button"
                                    id="langs"
                                    data-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="true"
                                    href="javascript:void(0)"
                                >
                                    <span>
                                        <?php echo $this->locale()->all()[$this->locale()->current()]; ?>
                                    </span>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="langs">
                                    <?php
                                        /**
                                         * @var \Zend\Mvc\Router\RouteMatch $routeMatch
                                         */
                                        $routeMatch = $this->getHelperPluginManager()
                                            ->getServiceLocator()
                                            ->get('Application')
                                            ->getMvcEvent()
                                            ->getRouteMatch();
                                        $routeToUse = null;

                                        if ($routeMatch && $routeMatch->getMatchedRouteName() == 'home') {
                                            $routeToUse = 'app/home';
                                        }

                                        foreach ($this->locale()->all() as $locale => $language):
                                            if($locale == $this->locale()->current()) {
                                                continue;
                                            }
                                    ?>
                                        <li>
                                            <a href="<?php echo $this->url($routeToUse, ['locale' => $locale], true) ?>">
                                                <?php echo $language ?>
                                            </a>
                                        </li>
                                    <?php endforeach ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="top-sosmed pull-right">
                        <a href="#" title=""><span class="fa fa-facebook"></span></a>
                        <a href="#" title=""><span class="fa fa-twitter"></span></a>
                        <a href="#" title=""><span class="fa fa-instagram"></span></a>
                        <a href="#" title=""><span class="fa fa-pinterest"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="<?php
                echo $this->url(
                    'app/home',
                    ['locale' => $this->locale()->current()]
                );
            ?>">
                <img
                    src="<?php echo $this->basePath('qizilqum/images/logo.png') ?>"
                    alt="<?php echo $this->translate('Title name') ?>"
                    title="<?php echo $this->translate('Title name') ?>"
                />
            </a>
        </div>

        <nav class="navbar-collapse collapse">
            <?php
                echo $this->navigation('Template\Navigation\Main')
                    ->menu()
                    ->setPartial('application/index/main-menu');
            ?>
        </nav>
    </div>
</div>

<?php echo $this->content; ?>

<!-- FOOTER SECTION -->
<?php echo $this->partial('application/partial/footer') ?>

<script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/jquery.min.js') ?>"></script>
<!--<script type='text/javascript' src='https://maps.google.com/maps/api/js?sensor=false&#038;ver=4.1.5'></script>-->
<script type='text/javascript' src="<?php echo $this->basePath('qizilqum/js/jqBootstrapValidation.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/bootstrap.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/owl.carousel.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/bootstrap-hover-dropdown.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/jquery.magnific-popup.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('qizilqum/js/script.js') ?>"></script>
<?php echo $this->inlineScript(); ?>
</body>
</html>