<div class="footer">
    <div class="f-desc">
        <div class="container">
            <div class="row">
                <?php
                    echo $this->navigation('Template\Navigation\Main')
                        ->menu()
                        ->setPartial('application/partial/footer-navigation');
                ?>
            </div>
        </div>
    </div>

    <div class="fcopy">
        <div class="container">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <p class="ftex">
                        <a href="http://each.uz/">
                            &copy; <?php echo date('Y', time()); ?> "FOR EACH SOFT" LTD
                        </a>
                    </p>
                </div>

                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                    <p class="pull-right">
                        <!-- START WWW.UZ TOP-RATING --><SCRIPT language="javascript" type="text/javascript">
                            <!--
                            top_js="1.0";top_r="id=16881&r="+escape(document.referrer)+"&pg="+escape(window.location.href);document.cookie="smart_top=1; path=/"; top_r+="&c="+(document.cookie?"Y":"N")
                            //-->
                        </SCRIPT>
                        <SCRIPT language="javascript1.1" type="text/javascript">
                            <!--
                            top_js="1.1";top_r+="&j="+(navigator.javaEnabled()?"Y":"N")
                            //-->
                        </SCRIPT>
                        <SCRIPT language="javascript1.2" type="text/javascript">
                            <!--
                            top_js="1.2";top_r+="&wh="+screen.width+'x'+screen.height+"&px="+
                                (((navigator.appName.substring(0,3)=="Mic"))?screen.colorDepth:screen.pixelDepth)
                            //-->
                        </SCRIPT>
                        <SCRIPT language="javascript1.3" type="text/javascript">
                            <!--
                            top_js="1.3";
                            //-->
                        </SCRIPT>
                        <SCRIPT language="JavaScript" type="text/javascript">
                            <!--
                            top_rat="&col=0063AF&t=ffffff&p=E6850F";top_r+="&js="+top_js+"";document.write('<a href="http://www.uz/ru/res/visitor/index?id=16881" target=_top><img src="http://cnt0.www.uz/counter/collect?'+top_r+top_rat+'" width=88 height=31 border=0 alt="Топ рейтинг www.uz"></a>')//-->
                        </SCRIPT><NOSCRIPT><A href="http://www.uz/ru/res/visitor/index?id=16881" target=_top><IMG height=31 src="http://cnt0.www.uz/counter/collect?id=16881&pg=http%3A//uzinfocom.uz&&col=0063AF&amp;t=ffffff&amp;p=E6850F" width=88 border=0 alt="Топ рейтинг www.uz"></A></NOSCRIPT><!-- FINISH WWW.UZ TOP-RATING -->
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>