<?php
$this->headTitle()->append($this->translate('Home soccer cup settings'))
    ->append($this->translate('Website config'));

$this->headLink()->appendStylesheet(
    $this->basePath('assets/admin/vendor/select2/select2.css')
);

$this->formElementErrors()->setMessageOpenFormat(
    '<ul class="list-group text-danger">
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                <i class="icon wb-alert" aria-hidden="true"></i>'
)->setMessageSeparatorString(
    '</li>
        <li class="list-group-item padding-0" style="padding-left:10px !important;">
                <i class="icon wb-alert" aria-hidden="true"></i>'
);
?>
    <div class="page-header">
        <h1 class="page-title"><?php echo $this->translate('Home soccer cup settings') ?></h1>
    </div>
    <div class="page-content">
        <?php echo $this->form()->openTag($form) ?>
        <div class="panel">
            <div class="panel-body container-fluid">

                <div class="form-group">
                    <?php echo $this->formLabel($form->get('cup')) ?>
                    <?php
                    echo $this->formSelect(
                        $form->get('cup')->setAttribute('data-plugin', 'select2')
                    )
                    ?>
                    <?php echo $this->formElementErrors($form->get('cup')) ?>
                </div>
                <a href="<?php echo $this->url(null, [], ['query' => ['delete' => true]], true) ?>" class="btn btn-default btn-outline <?php echo $form->get('cup')->getValue() ? '' : 'disabled' ?>"><?php echo $this->translate('Remove') ?></a>
            </div>
        </div>
        <div class="site-action">
            <button type="submit" class="btn-raised btn btn-success btn-floating" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Save changes')) ?>">
                <i class="wb-check animation-scale-up"></i>
            </button>
        </div>
        <?php echo $this->form()->closeTag($form) ?>
    </div>
<?php
$this->inlineScript()
    ->appendFile(
        $this->basePath('assets/admin/vendor/select2/select2.min.js')
    )
    ->appendFile(
        $this->basePath('assets/admin/js/components/select2.js')
    )
?>