<?php  
    $this->headTitle()->append($this->translate('Delete video info'))
    ->append($this->translate('Video'))
    ->append($this->translate('Media'));
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Delete video info') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo ($referer ?: $this->url(null, ['locale' => $this->locale()->current()])) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>"> 
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <div class="panel">
        <div class="panel-body">
            <h3><?php echo $this->translate('Do you really want to delete video info?') ?></h3>
            <p><?php echo $this->translate('This operation can not be prevented!') ?></p>
            <a href="<?php echo $this->url(null, [], ['query' => ['confirm' => true]], true) ?>" class="btn btn-default">
                <i class="icon wb-trash"></i>
                <span><?php echo $this->translate('Yes') ?></span>
            </a>
            <a href="<?php echo ($referer ?: $this->url(null, ['locale' => $this->locale()->current()])) ?>" class="btn btn-default">
                <i class="icon wb-close"></i>
                <span><?php echo $this->translate('No') ?></span>
            </a>
        </div>
    </div>
</div>