<?php
/**
 * @var \Soccer\Entity\Tournament $tournament
 * @var \Soccer\Entity\Season     $season
 * @var \Soccer\Entity\Stage      $stage
 */
$this->headTitle()->append($this->translate('Delete'));

if (isset($stage)) {
    $this->headTitle()->append(sprintf($this->translate('%s stage'), $stage->getLabel($this->locale()->current())));
}

$this->headTitle()
    ->append(sprintf($this->translate('Season %s'), $season->getLabel($this->locale()->current())))
    ->append($tournament->getLabel($this->locale()->current()))
    ->append($this->translate('Tournaments'))
    ->append($this->translate('Soccer'));
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Delete tour') ?></h1>
    <ol class="breadcrumb">
        <li>
            <a href="<?php echo $this->url('app/admin/soccer/tournaments', ['action' => 'index'], true) ?>"><?php echo $this->translate('Tournaments') ?></a>
        </li>
        <li>
            <a href="<?php echo $this->url('app/admin/soccer/seasons', ['tournament' => $tournament->getId(), 'action' => 'index'], true) ?>"><?php echo $tournament->getLabel($this->locale()->current()) ?></a>
        </li>
        <?php if (isset($stage) && $stage instanceof \Soccer\Entity\Stage): ?>
            <li>
                <a href="<?php echo $this->url('app/admin/soccer/stages', ['tournament' => $tournament->getId(), 'season' => $season->getId(), 'action' => 'index', 'id' => null], true) ?>"><?php printf('Season %s', $season->getLabel($this->locale()->current())) ?></a>
            </li>
            <li>
                <a href="<?php echo $this->url('app/admin/soccer/group-play', ['action' => 'index', 'id' => null, 'stage' => $stage->getParent()->getId()], true) ?>">
                    <span><?php echo $stage->getParent()->getLabel($this->locale()->current()) ?></span>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current(), 'tournament' => $tournament->getId(), 'season' => $season->getId(), 'stage' => $stage->getId()]) ?>"><?php printf($this->translate('Group %s'), $stage->getLabel($this->locale()->current())) ?></a>
            </li>
        <?php else: ?>
            <li>
                <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current(), 'tournament' => $tournament->getId(), 'season' => $season->getId()]) ?>"><?php printf($this->translate('Season %s'), $season->getLabel($this->locale()->current())) ?></a>
            </li>
        <?php endif; ?>
        <li class="active"><?php echo $this->translate('Delete') ?></li>
    </ol>
    <div class="page-header-actions">
        <a href="<?php echo $this->url(null, ['action' => 'index', 'id' => null], true) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>">
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <div class="panel">
        <div class="panel-body">
            <h3><?php echo $this->escapeHtml($this->translate("Are you sure?")); ?></h3>
            <p><?php echo $this->escapeHtml($this->translate("This action can not be prevented!")); ?></p>
            <a href="<?php echo $this->url(null, [], ['query' => ['confirm' => true],], true) ?>" class="btn btn-default">
                <i class="icon wb-trash"></i>
                <span><?php echo $this->escapeHtml($this->translate("Yes")); ?></span>
            </a>
            <a href="<?php echo $this->url(null, ['action' => 'index', 'id' => null], true) ?>" class="btn btn-default">
                <i class="icon wb-close"></i>
                <span><?php echo $this->escapeHtml($this->translate("No")); ?></span>
            </a>
        </div>
    </div>
</div>