<?php
$this->headTitle()->append($this->translate('Transfer'))
    ->append($this->translate('Soccer'));

$this->headLink()
    ->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-datepicker/bootstrap-datepicker.min.css')
    )
    ->appendStylesheet(
        $this->basePath('assets/admin/css/../fonts/material-design/material-design.css')
    )
    ->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-touchspin/bootstrap-touchspin.css')
    )
    ->appendStylesheet(
        $this->basePath('assets/admin/vendor/select2/select2.min.css')
    );

$this->inlineScript()
    ->appendFile($this->basePath('assets/admin/vendor/bootstrap-datepicker/bootstrap-datepicker.min.js'))
    ->appendFile($this->basePath('assets/admin/js/components/bootstrap-datepicker.min.js'))
    ->appendFile($this->basePath('assets/admin/vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js'))
    ->appendFile($this->basePath('assets/admin/js/components/bootstrap-touchspin.js'))
    ->appendFile($this->basePath('assets/admin/vendor/select2/select2.min.js'))
    ->appendFile($this->basePath('assets/admin/js/components/select2.min.js'));

$this->formElementErrors()->setMessageOpenFormat(
    '<ul class="list-group text-danger">
                <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
)->setMessageSeparatorString(
    '</li>
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                    <i class="icon wb-alert" aria-hidden="true"></i>'
);
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Transfer player') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $this->url('app/admin/soccer/club', ['action' => 'players', 'id' => $club->getId()], true) ?>" class="btn btn-sm btn-icon btn-danger" data-toggle="tooltip" data-container="body" data-original-title="<?php echo $this->translate('Cancel') ?>">
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel">
        <div class="panel-body">
            <div class="form-group">
                <h5><?php echo $this->formLabel($form->get('date')) ?></h5>
                <div class="input-group">
                    <?php
                    echo $this->formText(
                        $form->get('date')
                            ->setAttribute('class', 'form-control')
                            ->setAttribute('data-plugin', 'datepicker')
                            ->setAttribute('data-format', 'dd.mm.yyyy')
                            ->setValue(date('d.m.Y'))
                    );
                    ?>
                    <span class="input-group-addon">
                                <i class="icon wb-calendar"></i>
                            </span>
                </div>
                <?php echo $this->formElementErrors($form->get('date')); ?>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <h5><?php echo $this->formLabel($form->get('club')) ?></h5>
                        <?php
                        echo $this->formSelect(
                            $form->get('club')
                                ->setAttribute('class', 'form-control')
                                ->setAttribute('data-plugin', 'select2')
                                ->setAttribute('id', 'clubSelect')
                        );
                        echo $this->formElementErrors($form->get('club'));
                        ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <h5><?php echo $this->formLabel($form->get('number')) ?></h5>
                        <?php
                        echo $this->formText(
                            $form->get('number')
                                ->setAttribute('class', 'form-control')
                                ->setAttribute('data-plugin', 'TouchSpin')
                                ->setAttribute('data-max', 999)
                                ->setAttribute('data-min', 0)
                                ->setAttribute('placeholder', '-')
                        );
                        ?>
                        <?php echo $this->formElementErrors($form->get('number')); ?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <h5><?php echo $this->formLabel($form->get('position')) ?></h5>
                <?php
                echo $this->formSelect(
                    $form->get('position')
                        ->setAttribute('class', 'form-control')
                        ->setAttribute('data-plugin', 'select2')
                        ->setAttribute('id', 'positionSelect')
                );
                echo $this->formElementErrors($form->get('position'));
                ?>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success btn-raised">
                    <i class="icon md-check"></i>
                    <span><?php echo $this->translate('Save') ?></span>
                </button>
                <a href="<?php echo $this->url('app/admin/soccer/club', ['action' => 'players', 'id' => $club->getId()], true) ?>" class="btn btn-raised btn-danger">
                    <i class="icon md-close"></i>
                    <?php echo $this->translate('Cancel') ?>
                </a>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form) ?>
</div>
