<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <base href="<?php echo $this->basePath('/') ?>">
    <meta charset="utf-8">
    <?php echo $this->headTitle()->append($this->translate('Administrative control panel'))->append($this->translate('Title name'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('qizilqum/images/favicon.png')])
            ->prependStylesheet($this->basePath('assets/admin/fonts/font-awesome/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/fonts/brand-icons/brand-icons.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/fonts/web-icons/web-icons.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/dashboard/v1.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/../fonts/roboto/roboto.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/../fonts/weather-icons/weather-icons.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/toastr/toastr.css'))
            /*->prependStylesheet($this->basePath('assets/admin/vendor/jvectormap/jquery-jvectormap.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/chartist-js/chartist.css'))*/
            ->prependStylesheet($this->basePath('assets/admin/vendor/flag-icon-css/flag-icon.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/slidepanel/slidePanel.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/intro-js/introjs.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/switchery/switchery.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/asscrollable/asScrollable.css'))
            ->prependStylesheet($this->basePath('assets/admin/vendor/animsition/animsition.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/site.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/bootstrap-extend.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/bootstrap.min.css'));
    ?>
    <?php echo $this->headStyle(); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('assets/admin/vendor/breakpoints/breakpoints.js'))
        ->prependFile($this->basePath('assets/admin/vendor/modernizr/modernizr.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
    <script>
        Breakpoints();
    </script>

</head>
<body class="<?php if (isset($this->tag['body']['class']) && is_array($this->tag['body']['class'])) echo join($this->tag['body']['class'], ' ') ?>">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle hamburger hamburger-close navbar-toggle-left hided" data-toggle="menubar">
                <span class="sr-only">Toggle navigation</span>
                <span class="hamburger-bar"></span>
            </button>
            <button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-collapse" data-toggle="collapse"> <i class="icon wb-more-horizontal" aria-hidden="true"></i>
            </button>
            <button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-search" data-toggle="collapse">
                <span class="sr-only">Toggle Search</span> <i class="icon wb-search" aria-hidden="true"></i>
            </button>
            <div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
                <img class="navbar-brand-logo" src="<?php echo $this->basePath('qizilqum/images/logo.png') ?>" title="<?php echo $this->escapeHtmlAttr($this->translate('Brand name')) ?>">
                <span class="navbar-brand-text"><?php echo $this->translate('Brand name') ?></span>
            </div>
        </div>

        <div class="navbar-container container-fluid">
            <!-- Navbar Collapse -->
            <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
                <!-- Navbar Toolbar -->
                <ul class="nav navbar-toolbar">
                    <li class="hidden-float" id="toggleMenubar">
                        <a data-toggle="menubar" href="#" role="button">
                            <i class="icon hamburger hamburger-arrow-left"><span class="sr-only">Toggle menubar</span>
                                <span class="hamburger-bar"></span></i> 
                        </a>
                    </li>
                    <li class="hidden-xs" id="toggleFullscreen">
                        <a class="icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
                            <span class="sr-only">Toggle fullscreen</span>
                        </a>
                    </li>
                </ul>
                <!-- End Navbar Toolbar -->

                <!-- Navbar Toolbar Right -->
                <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)" data-animation="slide-bottom" aria-expanded="false" role="button">
                            <span class="flag-icon flag-icon-<?php echo strtolower(substr($this->locale()->current(), strrpos($this->locale()->current(), '-') + 1)) ?>"></span>
                            <?php if (strtolower($this->locale()->current()) == 'uz-latn-uz'): ?>
                                <span>L</span>
                            <?php endif ?>
                            <?php if (strtolower($this->locale()->current()) == 'uz-cyrl-uz'): ?>
                                <span>K</span>
                            <?php endif ?>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <?php foreach ($this->locale()->all() as $locale => $language): ?>
                                <?php if ($this->locale()->current() == $locale) continue; ?>
                                <li>
                                    <?php
                                        $href = $this->url('app/admin', ['locale' => $locale]);

                                        if (null !== $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()) {
                                            $href = $this->url(null, ['locale' => $locale], true);
                                        }
                                    ?>
                                    <a title="<?php echo $this->escapeHtmlAttr($language) ?>" href="<?php echo $href ?>">
                                        <span class="flag-icon flag-icon-<?php echo strtolower(substr($locale, strrpos($locale, '-') + 1)) ?>"></span>
                                        <span class="hidden-xs"><?php echo $language ?></span>
                                    </a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" href="javascript:void(0)" title="<?php echo $this->escapeHtmlAttr($this->translate("Notifications")); ?>" data-animation="slide-bottom">
                            <i class="icon wb-bell" aria-hidden="true"></i>
                            <span class="badge badge-danger up">2</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
                            <li class="dropdown-menu-header" role="presentation">
                                <h5><?php echo $this->translate('Notifications') ?></h5>
                                <span class="label label-round label-danger"><?php printf($this->translate('New %s'), 2 /* @todo make it real */) ?></span>
                            </li>

                            <li class="list-group" role="presentation">
                                <div data-role="container">
                                    <div data-role="content">
                                        <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                                            <div class="media">
                                                <div class="media-left padding-right-10">
                                                    <i class="icon wb-calendar bg-red-600 white icon-circle" aria-hidden="true"></i>
                                                </div>
                                                <div class="media-body">
                                                    <h6 class="media-heading"><?php echo $this->translate('The details of match was not added') ?></h6>
                                                    <time class="media-meta" datetime="2015-06-11T14:05:00+08:00">2 days ago</time>
                                                </div>
                                            </div>
                                        </a>
                                        <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                                            <div class="media">
                                                <div class="media-left padding-right-10">
                                                    <i class="icon wb-file bg-blue-600 white icon-circle" aria-hidden="true"></i>
                                                </div>
                                                <div class="media-body">
                                                    <h6 class="media-heading"><?php echo $this->translate('Posted scheduled article') ?></h6>
                                                    <time class="media-meta" datetime="2015-06-10T13:50:18+08:00">3 days ago</time>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </li>
                            <li class="dropdown-menu-footer" role="presentation">
                                <a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">
                                    <i class="icon wb-settings" aria-hidden="true"></i>
                                </a>
                                <a href="javascript:void(0)" role="menuitem">All notifications</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="navbar-avatar dropdown-toggle" title="<?php echo $this->escapeHtmlAttr($this->identity()->name) ?>" data-toggle="dropdown" href="#" aria-expanded="false" data-animation="slide-bottom" role="button">
                            <span class="avatar avatar-online">
                                <span class="icon wb-user icon-2x" aria-hidden="true"></span>
                                <i></i>
                            </span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li role="presentation">
                                <a href="<?php echo $this->url('app/admin/user/profile', ['locale' => $this->locale()->current()]) ?>" role="menuitem">
                                    <i class="icon wb-user" aria-hidden="true"></i>
                                    <?php echo $this->translate('Profile') ?>
                                </a>
                            </li>
                            <li class="divider" role="presentation"></li>
                            <li role="presentation">
                                <a href="<?php echo $this->url('logout', ['locale' => $this->locale()->current()]) ?>" role="menuitem">
                                    <i class="icon wb-power" aria-hidden="true"></i>
                                    <?php echo $this->translate('Logout') ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- End Navbar Toolbar Right --> </div>
            <!-- End Navbar Collapse -->
        </div>
    </nav>
    <div class="site-menubar">
        <div class="site-menubar-body">
            <div>
                <div>
                    <ul class="site-menu">
                        <?php 
                            echo $this->navigation('Zend\Navigation\Admin')
                            ->menu()
                            ->setPartial('admin/partial/admin-menu');
                        ?>
                    </ul>

                    <div class="site-menubar-section">
                        <h5 style="font-size: 0.85em;">
                            <?php  
                                $sizeString = function ($size) {
                                    $i=0;
                                    $iec = array("B", "Kb", "Mb", "Gb", "Tb");
                                    while (($size/1024)>1) {
                                        $size=$size/1024;
                                        $i++;}
                                    return(round($size,1)." ".$iec[$i]); 
                                };

                                $diskSpace = disk_free_space(".");
                                $totalDiskSpace = disk_total_space(".");
                                $filledSpacePercent = 100 - $diskSpace * 100 / $totalDiskSpace;
                            ?>
                            <?php echo $this->translate('Available space') ?>:
                            <span class="pull-right"><?php echo $sizeString($diskSpace) ?></span>
                        </h5>
                        <div class="progress progress-xs">
                            <div class="progress-bar <?php echo ($filledSpacePercent > 90 ? 'progress-bar-danger' : ''); echo (($filledSpacePercent > 80 && $filledSpacePercent <= 90) ? 'progress-bar-warning' : '') ?> active" style="width: <?php echo round($filledSpacePercent, 2) ?>%;" role="progressbar"></div>
                        </div>
                        <!-- <h5>
                            Release
                            <span class="pull-right">60%</span>
                        </h5>
                        <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-warning" style="width: 60%;" role="progressbar"></div>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>

        <div class="site-menubar-footer">
            <a href="<?php echo $this->url('app/admin/user/profile', ['locale' => $this->locale()->current()]) ?>" class="fold-show" data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Settings')) ?>">
                <span class="icon wb-settings" aria-hidden="true"></span>
            </a>
            <a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Lock')) ?>">
                <span class="icon wb-eye-close" aria-hidden="true"></span>
            </a>
            <a href="<?php echo $this->url('logout', ['locale' => $this->locale()->current()]) ?>" data-placement="top" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Logout')) ?>">
                <span class="icon wb-power" aria-hidden="true"></span>
            </a>
        </div>
    </div>
    <div class="site-gridmenu">
        <ul>
            <?php echo $this->navigation('Zend\Navigation\Adminapps')->menu()->setPartial('admin/partial/admin-apps-menu') ?>
        </ul>
    </div>

    <!-- Page -->
    <div class="page <?php if (isset($this->tag['div.page']['class']) && is_array($this->tag['div.page']['class'])) echo join($this->tag['div.page']['class'], ' ') ?>">
        <?php echo $this->content; ?>
    </div>
    <!-- End Page -->

    <!-- Footer -->
    <div class="clearfix"></div>
    <footer class="site-footer">
        <span class="site-footer-legal">© <?php echo date('Y') ?> Foreach.Soft Ltd.</span>
    </footer>

    <!-- Core  -->
    <script src="<?php echo $this->basePath('assets/admin/vendor/jquery/jquery.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/bootstrap/bootstrap.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/animsition/jquery.animsition.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/asscroll/jquery-asScroll.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/mousewheel/jquery.mousewheel.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/asscrollable/jquery.asScrollable.all.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/ashoverscroll/jquery-asHoverScroll.js') ?>"></script>

    <!-- Plugins -->
    <script src="<?php echo $this->basePath('assets/admin/vendor/switchery/switchery.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/intro-js/intro.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/screenfull/screenfull.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/slidepanel/jquery-slidePanel.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/vendor/toastr/toastr.js') ?>"></script>

    <!-- Scripts -->
    <script src="<?php echo $this->basePath('assets/admin/js/core.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/js/site.js') ?>"></script>

    <script src="<?php echo $this->basePath('assets/admin/js/sections/menu.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/js/sections/menubar.js') ?>"></script>

    <script src="<?php echo $this->basePath('assets/admin/js/configs/config-colors.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/js/configs/config-tour.js') ?>"></script>

    <script src="<?php echo $this->basePath('assets/admin/js/components/asscrollable.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/js/components/animsition.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/js/components/slidepanel.js') ?>"></script>
    <script src="<?php echo $this->basePath('assets/admin/js/components/switchery.js') ?>"></script>
    
    
    <?php echo $this->inlineScript() ?>
    <script>
        (function(document, window, $) {
            'use strict';

            var Site = window.Site;
            $(document).ready(function() {
                Site.run();
            });
        })(document, window, jQuery);
    </script>
    <?php echo $this->partial('admin/partial/flashmessage') ?>
</body>
</html>
