<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$this->headLink()
    ->appendStylesheet($this->basePath('fonts/font-awesome/font-awesome.min.css'))
?>
<style>
    section.tournament-season {
        padding: 20px 0;
        margin: 0 -15px;
    }
</style>
<section class="page-breadcrumbs">
    <div class="container">
        <ul class="breadcrumb">
            <li>
                <a href="javascript:void(0);">Home</a>
            </li>
            <li>
                <a href="javascript:void(0);">Uzbekistan higher league, 2016</a>
            </li>
        </ul>
    </div>
</section>
<section class="tournament-season bg-grey-200">
    <div class="container">
        <h1 class="section-title">Uzbekistan higher league, 2016</h1>
        <div class="row">
            <div class="col-md-5">
                <div class="panel matches-panel">
                    <div class="panel-heading">
                        <span class="panel-title">Matches</span>
                    </div>
                    <div class="panel-body">
                        <div class="well text-center">
                            <h1><i class="icon md-inbox"></i></h1>
                            <h3>Content will be added soon</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="panel matches-panel">
                    <div class="panel-heading">
                        <p class="panel-title">Table</p>
                    </div>
                    <div class="panel-body">
                        <div class="table-reponsive">
                            <table class="table table-striped text-center">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th class="text-left">Club</th>
                                    <th>Played</th>
                                    <th>W</th>
                                    <th>D</th>
                                    <th>L</th>
                                    <th>F</th>
                                    <th>A</th>
                                    <th class="hidden-xs"><abbr title="Goal diffrence">GD</abbr></th>
                                    <th>Points</th>
                                    <th>Form</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>1</td>
                                    <td class="text-left">Bunyodkor</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">29-5</td>
                                    <td>37</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td class="text-left">Lokomotiv</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">34-11</td>
                                    <td>36</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td class="text-left">Nasaf</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">23-13</td>
                                    <td>28</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td class="text-left">Metallurg</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">24-17</td>
                                    <td>28</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td class="text-left">Pakhtakor</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">26-16</td>
                                    <td>27</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td class="text-left">Kizilkum</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">19-16</td>
                                    <td>23</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>7</td>
                                    <td class="text-left">Bukhara</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">17-15</td>
                                    <td>23</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>8</td>
                                    <td class="text-left">Olmalyk</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">24-26</td>
                                    <td>21</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>9</td>
                                    <td class="text-left">Neftchi</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">14-21</td>
                                    <td>21</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>10</td>
                                    <td class="text-left">Mashal</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">18-19</td>
                                    <td>19</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>11</td>
                                    <td class="text-left">Shurtan</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">27-30</td>
                                    <td>17</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>12</td>
                                    <td class="text-left">Soghdiyona</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">12-18</td>
                                    <td>16</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>13</td>
                                    <td class="text-left">Navbakhor</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">21-24</td>
                                    <td>14</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>14</td>
                                    <td class="text-left">Andijon</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">13-30</td>
                                    <td>9</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>15</td>
                                    <td class="text-left">Kokand-1912</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">13-33</td>
                                    <td>9</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                <tr>
                                    <td>16</td>
                                    <td class="text-left">Obod</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>15</td>
                                    <td>35</td>
                                    <td>22</td>
                                    <td class="hidden-xs">11-31</td>
                                    <td>8</td>
                                    <td class="form">
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square yellow-500"></i>
                                        <i class="icon fa fa-square red-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                        <i class="icon fa fa-square green-500"></i>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>