<!-- BANNER -->
<div class="section subbanner">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="caption">
                    <?php echo $this->translate('Team members') ?>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- ABOUT SECTION -->
<div class="section singlepage" style="margin-top: 30px;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <?php echo $this->playerCards('application/index/player-cards-page') ?>
            </div>
        </div>
    </div>
</div>