<div class="section gallery bg-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="page-title">
                    <h2 class="lead"><?php echo $this->translate('Gallery') ?></h2>
                    <div class="border-style"></div>
                </div>
            </div>
        </div>
        <div class="row popup-gallery">
        <?php
            foreach ($galleriesInfo as $key => $value):
                foreach($value->getGallery()->getPhotos() as $k => $v) :
        ?>
                <div class="col-xs-4 col-sm-3 col-md-3">
                    <div class="w-item">
                        <a
                            href="<?php echo $v->getThumbnail() ?>"
                            title="<?php //echo $v->getTitle() ?>"
                        >
                            <img
                                src="<?php echo $v->getThumbnail() ?>"
                                class="img-responsive"
                            >
                            <div class="project-info">
                                <div class="project-icon">
                                    <span class="fa fa-search"></span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </div>

        <div class="loadmore">
            <a href="<?php echo $this->url('app/media/galleries', ['locale' => $this->locale()->current()]) ?>" title="<?php echo $this->translate('Galleries') ?>">
                <?php echo $this->translate('Galleries') ?>
            </a>
        </div>

    </div>
</div>