<?php 
    $this->headTitle()->append($this->translate('Edit photo information'));

    $form->setAttribute('action', $this->url(null, ['locale' => $this->locale()->current(), 'action' => 'editPhotoInfoModal', 'id' => $photoInfo->getId()]));
?>
<div class="modal fade">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><?php echo $this->translate('Edit photo information') ?></h4>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <div class="modal-body">
                    <div class="form-group">
                        <label><?php echo $this->translate('Language') ?></label>
                        <div class="input-group">
                            <span class="input-group-addon"> 
                                <i class="icon wb-flag" aria-hidden="true"></i>
                            </span>
                            <input disabled="" value="<?php echo $this->escapeHtmlAttr($this->locale()->all()[$photoInfo->getLocale()]) ?>" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group <?php echo $form->get('title')->getMessages() ? 'has-error' : '' ?>">
                        <?php echo $this->formLabel($form->get('title')) ?>
                        <div class="input-group">
                            <span class="input-group-addon"> 
                                <i class="icon wb-pencil" aria-hidden="true"></i>
                            </span>
                            <?php 
                                echo $this->formText(
                                    $form->get('title')
                                    ->setAttribute('class', 'form-control')
                                )
                            ?>
                        </div> 
                        <?php echo $this->formElementErrors($form->get('title')) ?>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save changes') ?></button>
            </div>
            <?php echo $this->form()->closeTag($form) ?>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->