<?php  
    $this->headTitle()->append($this->translate('Edit gallery'));

    $this->headLink()->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-datepicker/bootstrap-datepicker.css')
    )->appendStylesheet(
        $this->basePath('assets/admin/vendor/bootstrap-sweetalert/sweet-alert.css')
    );

    $this->headStyle()->appendStyle(
        "
            .info {
                position: relative;
                padding: 50px 15px 15px 50px;
                background-color: #f3f7fa;
                border: 1px solid #eee;
            }
        "
    );

    $this->formElementErrors()->setMessageOpenFormat(
        '<ul class="list-group text-danger">
            <li class="list-group-item padding-0" style="padding-left:10px !important;">
                <i class="icon wb-alert" aria-hidden="true"></i>'
    )->setMessageSeparatorString(
        '</li>
        <li class="list-group-item padding-0" style="padding-left:10px !important;">
                <i class="icon wb-alert" aria-hidden="true"></i>'
    );

    $form->setAttribute(
        'action', 
        $this->url(
            null, 
            [
                'action' => 'editGallery',
                'id'     => $photoGallery->getId()
            ],
            true
        )
    )
    ->prepare();
?>
<div class="page-header">
    <h1 class="page-title"><?php echo $this->translate('Edit gallery') ?></h1>
    <div class="page-header-actions">
        <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current()]) ?>" class="btn btn-danger" data-toggle="tooltip" data-placement="left" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Cancel')) ?>"> 
            <i class="icon wb-close" aria-hidden="true"></i>
        </a>
    </div>
</div>
<div class="page-content">
    <!-- Panel -->
    <div class="panel">
        <div class="panel-body container-fluid">
            <div class="row">
                <?php echo $this->form()->openTag($form) ?>
                <div class="col-md-12">
                    <div class="form-group <?php echo $form->get('created_date')->getMessages() ? 'has-error' : '' ?>">
                        <?php echo $this->formLabel($form->get('created_date')) ?>
                        <div class="input-group">
                            <span class="input-group-addon"> 
                                <i class="icon wb-calendar" aria-hidden="true"></i>
                            </span>
                            <?php 
                                echo $this->formText(
                                    $form->get('created_date')
                                    ->setAttribute('class', 'form-control')
                                    ->setAttribute('data-plugin', 'datepicker')
                                    ->setAttribute('data-format', 'dd.mm.yyyy')
                                ),
                                $this->formElementErrors($form->get('created_date'))
                            ?>
                        </div> 
                    </div>
                    <button type="submit" class="btn btn-success">
                        <i class="icon wb-check"></i>
                        <span><?php echo $this->translate('Save changes') ?></span>
                    </button>
                    <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current()]) ?>" class="btn btn-danger" data-toggle="tooltip" data-original-title="<?php echo $this->escapeHtmlAttr($this->translate('Cancel')) ?>"> 
                        <i class="icon wb-close" aria-hidden="true"></i>
                        <span><?php echo $this->translate('Cancel') ?></span>
                    </a>
                    <br><br>
                    <div class="clearfix"></div>
                </div>
                <?php echo $this->form()->closeTag($form) ?>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><?php echo $this->translate('Info') ?></label>
                        <?php if ($photoGallery->getInfo()->count()): ?>
                            <div class="row">
                            <?php foreach ($photoGallery->getInfo() as $info): ?>
                                <div class="col-sm-3">
                                    <div class="info">
                                        <div class="ribbon ribbon-warning ribbon-reverse">
                                            <span class="ribbon-inner"><?php echo $this->locale()->all()[$info->getLocale()] ?></span>
                                        </div>
                                        <h5>
                                            <?php echo $this->translate('Title') ?>: <b><?php echo $info->getTitle() ?></b>
                                        </h5>
                                        <hr style="margin: 10px 0;">
                                        <div class="btn-group" style="margin: 0 auto;">
                                            <button data-toggle="tooltip" title="<?php echo $this->escapeHtmlAttr($this->translate('Edit')) ?>" data-id="<?php echo $info->getId() ?>" class="btn btn-primary edit-description">
                                                <i class="icon wb-pencil"></i>
                                            </button>
                                            <button data-href="<?php echo $this->url(null, ['action' => 'deleteGalleryInfo', 'id' => $info->getId()], ['query' => ['return' => $this->url(null, [], true), 'confirm' => true]], true) ?>" data-toggle="tooltip" title="<?php echo $this->escapeHtmlAttr($this->translate('Delete')) ?>" class="btn btn-danger confirm-action">
                                                <i class="icon wb-trash"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach ?>
                            </div>
                            <br>
                        <?php else: ?>
                            <div class="well text-center">
                                <h1 class="text-warning">
                                    <i class="icon wb-warning"></i>
                                </h1>
                                <h3><?php echo $this->translate('No information provided yet!') ?></h3>
                            </div>
                        <?php endif ?>
                        <?php if ($locales): ?>
                            <?php  
                                $infoForm->setAttribute(
                                    'action', 
                                    $this->url(
                                        null, 
                                        [
                                            'locale' => $this->locale()->current(), 
                                            'action' => 'addGalleryInfo',
                                            'id'     => $photoGallery->getId(),
                                        ]
                                    )
                                )
                                ->prepare();
                            ?>
                            <?php echo $this->form()->openTag($infoForm) ?>
                                <div class="form-group <?php echo $infoForm->get('locale')->getMessages() ? 'has-error' : '' ?>">
                                    <?php echo $this->formLabel($infoForm->get('locale')) ?>
                                    <div class="input-group">
                                        <span class="input-group-addon"> 
                                            <i class="icon wb-flag" aria-hidden="true"></i>
                                        </span>
                                        <?php 
                                            echo $this->formSelect(
                                                $infoForm->get('locale')
                                                ->setAttribute('class', 'form-control')
                                            )
                                        ?>
                                    </div> 
                                    <?php echo $this->formElementErrors($infoForm->get('locale')) ?>
                                </div>
                                <div class="form-group <?php echo $infoForm->get('title')->getMessages() ? 'has-error' : '' ?>">
                                    <?php echo $this->formLabel($infoForm->get('title')) ?>
                                    <div class="input-group">
                                        <span class="input-group-addon"> 
                                            <i class="icon wb-pencil" aria-hidden="true"></i>
                                        </span>
                                        <?php 
                                            echo $this->formText(
                                                $infoForm->get('title')
                                                ->setAttribute('class', 'form-control')
                                            )
                                        ?>
                                    </div> 
                                    <?php echo $this->formElementErrors($infoForm->get('title')) ?>
                                </div>
                                <div class="text-center form-group">
                                    <button class="btn btn-default">
                                        <i class="icon wb-plus"></i>
                                        <span><?php echo $this->translate('Add') ?></span>
                                    </button>
                                </div>
                            <?php echo $this->form()->closeTag($infoForm) ?>
                        <?php endif ?>
                    </div>
                </div>
                <?php if ($photoGallery->getPhotos()->count()): ?>
                    <div class="col-md-12">
                        <label><?php echo $this->translate('Photos') ?></label>
                        <div class="row">
                            <?php foreach ($photoGallery->getPhotos() as $photo): ?>
                                <div class="col-sm-4 col-md-3" style="margin-bottom: 30px;">
                                    <figure class="overlay overlay-hover">
                                        <img class="overlay-figure img-responsive img-thumbnail" src="<?php echo $this->basePath($photo->getSmallThumbnail()) ?>">                  
                                        <figcaption class="overlay-panel overlay-background overlay-fade text-center vertical-align">
                                            <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current(), 'action' => 'editPhoto', 'id' => $photo->getId()], ['query' => ['return' => $this->url(null, [],true)]]) ?>" class="btn btn-outline btn-primary btn-icon vertical-align-middle" data-toggle="tooltip" title="<?php echo $this->escapeHtmlAttr($this->translate('Edit info')) ?>">
                                                <i class="icon wb-pencil"></i>
                                            </a> &nbsp;
                                            <button data-href="<?php echo $this->url(null, ['action' => 'deletePhoto', 'id' => $photo->getId()], ['query' => ['return' => $this->url(null, [], true), 'confirm' => true]], true) ?>" class="btn btn-outline btn-primary btn-icon vertical-align-middle confirm-action" data-toggle="tooltip" title="<?php echo $this->escapeHtmlAttr($this->translate('Delete')) ?>">
                                                <i class="icon wb-trash"></i>
                                            </button>
                                        </figcaption>
                                    </figure>
                                </div>
                            <?php endforeach ?>                        
                        </div>
                    </div>                    
                <?php endif ?>
                <div class="text-center">
                    <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current(), 'action' => 'addPhotosToGallery', 'id' => $photoGallery->getId()]) ?>" class="btn btn-default btn-lg">
                        <i class="icon wb-gallery" style="margin: 0;"></i>
                        <?php echo $this->translate('Add more images') ?>
                    </a>
                </div>
                <br>
                <div class="col-md-12">
                    <a href="<?php echo $this->url(null, ['locale' => $this->locale()->current()]) ?>" class="btn btn-success">
                        <i class="icon wb-check"></i>
                        <span><?php echo $this->translate('Done and exit') ?></span>
                    </a>
                    <?php if ($photoGallery->getStatus() === \Media\Entity\PhotoGallery::STATUS_DRAFT): ?>
                        <a href="<?php echo $this->url(null, ['action' => 'finishCreatingGallery'], true) ?>" class="btn btn-default">
                            <i class="icon wb-bookmark"></i>
                            <span><?php echo $this->translate('Mark as finished') ?></span>
                        </a>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
    <!-- End Panel -->
</div>
<?php  
    $this->inlineScript()->appendFile(
        $this->basePath('assets/admin/vendor/bootstrap-sweetalert/sweet-alert.js')
    )
    ->appendScript(
        "
            $('.confirm-action').click(
                function () {
                    var btn = $(this);
                    
                    if (!btn.data('href')) {
                        return;
                    }

                    swal({
                      title: '".$this->escapeJs($this->translate('Are you sure'))."?',
                      text: '".$this->escapeJs($this->translate('This operation can not be prevented'))."!',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#DD6B55',
                      confirmButtonText: '".$this->escapeJs($this->translate('Yes'))."',
                      cancelButtonText: '".$this->escapeJs($this->translate('No'))."',
                      closeOnConfirm: false,
                    },
                    function() {
                      swal('".$this->escapeJs($this->translate('Cancelled'))."!',
                        '".$this->escapeJs($this->translate('New gallery creation cancelled'))."!',
                        'success');

                      location.href = btn.data('href');
                    });
                }
            );
        "   
    )
    ->appendScript(
        "
            $('.edit-description').click(
                function () {
                    if (!$(this).data('id')) {
                        return;
                    }
                    
                    var id = $(this).data('id');
                    var target = '".$this->url(null, ['action' => 'editGalleryDescriptionStep', 'id' => ':id'], true)."';

                    var showModal = function () {
                        $('.edit-description').attr('disabled', '1');
                        $.ajax(
                            target.replace(':id', id),
                            {
                                success: function (response) {
                                    response = $(response);
                                    var mdl  = response;
                                    var form = response.find('form');

                                    form.submit(formSubmit);
                                    mdl.on('hidden.bs.modal', onModalHide);

                                    $('body').append(response);
                                    mdl.modal('show').focus();
                                    $('.edit-description').removeAttr('disabled', '1');
                                },
                                error: function (xhr) {
                                    console.log(xhr);

                                    alert('".$this->escapeJs($this->translate('Something went wrong') . ",\n" . $this->translate('Please try again')).".');
                                }
                            }
                        );
                    };

                    var onModalHide = function () {
                        $(this).nextAll('.modal-backdrop').remove();
                        $(this).remove();
                    }

                    var formSubmit = function (e) {
                        e.preventDefault();
                        var _form = $(this);

                        $.ajax(
                            _form.attr('action'),
                            {
                                method: _form.attr('method') || 'POST',
                                data: _form.serialize(),
                                success: function (response) {
                                    if (typeof response === 'string') {
                                        var _mdl  = _form.parents('.modal');
                                        
                                        _mdl.modal('hide');

                                        setTimeout(
                                            function () {
                                                _mdl.remove();
                                                response = $(response);
                                                var mdl  = response;
                                                var form = response.find('form');

                                                form.submit(formSubmit);
                                                mdl.on('hidden.bs.modal', onModalHide);

                                                $('body').append(response);
                                                mdl.modal('show').focus();
                                            }, 
                                            1000
                                        );
                                    }

                                    if (typeof response === 'object') {
                                        location.reload();
                                    }
                                },
                                error: function (xhr) {
                                    console.log(xhr);

                                    alert('".$this->escapeJs($this->translate('Something went wrong') . ",\n" . $this->translate('Please try again')).".');
                                }
                            }
                        );

                        return false;
                    };

                    showModal();
                }
            );
        "
    )
    ->appendFile(
        $this->basePath('assets/admin/vendor/bootstrap-datepicker/bootstrap-datepicker.js')
    )->appendFile(
        $this->basePath('assets/admin/js/components/bootstrap-datepicker.js')
    );
?>